services:
  rabbitma:
    image: rabbitmq:3-management
    container_name: micro-chat-rabbitmq
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    networks:
      - micro-chat-network

  user-db:
    image: postgres:16
    container_name: micro-chat-user-db
    environment:
      POSTGRES_DB: ${USER_DB_NAME:-micro-chat_user_service}
      POSTGRES_USER: ${USER_DB_USER:-micro-chat_user}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD:-micro-chat_password}
    ports:
      - '${USER_DB_PORT:-5432}:5432'
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - micro-chat-network

  auth-db:
    image: mysql:8.0
    container_name: micro-chat-auth-db
    environment:
      MYSQL_DATABASE: ${AUTH_DB_NAME:-micro-chat_auth_service}
      MYSQL_USER: ${AUTH_DB_USER:-micro-chat_auth_user}
      MYSQL_PASSWORD: ${AUTH_DB_PASSWORD:-micro-chat_auth_password}
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD:-root_password}
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    ports:
      - '${AUTH_DB_PORT:-3306}:3306'
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - micro-chat-network

volumes:
  user-db-data:
  auth-db-data:

networks:
  micro-chat-network:
    driver: bridge
